// A separate pool: practice must never disclose a future ranked pack.
export const practiceQuestions = [
  [
    "Geography",
    "Which continent is Egypt in?",
    ["Asia", "Africa", "Europe", "Oceania"],
    "Africa",
    "Egypt is in northeastern Africa, with the Sinai Peninsula extending into Asia.",
    "Look to the continent containing the Sahara.",
    "https://www.britannica.com/place/Egypt",
  ],
  [
    "History",
    "Who was the first president of the United States?",
    ["Thomas Jefferson", "John Adams", "George Washington", "James Madison"],
    "George Washington",
    "Washington served as the first US president from 1789 to 1797.",
    "He led the Continental Army.",
    "https://www.whitehouse.gov/about-the-white-house/presidents/george-washington/",
  ],
  [
    "Movies",
    "Which film features the character Woody the cowboy?",
    ["Shrek", "Toy Story", "Finding Nemo", "Cars"],
    "Toy Story",
    "Woody is a central character in Pixar’s Toy Story.",
    "His best friend goes to infinity and beyond.",
    "https://www.pixar.com/toy-story",
  ],
  [
    "Music",
    "How many strings does a standard violin have?",
    ["3", "4", "5", "6"],
    "4",
    "A standard violin has four strings tuned G, D, A, and E.",
    "The same number as the usual members of a string quartet.",
    "https://www.britannica.com/art/violin",
  ],
  [
    "Science",
    "What is the chemical formula for water?",
    ["CO2", "O2", "H2O", "NaCl"],
    "H2O",
    "A water molecule consists of two hydrogen atoms and one oxygen atom.",
    "Two atoms of the lightest element and one of another.",
    "https://www.britannica.com/science/water",
  ],
  [
    "Food",
    "Which fruit is traditionally used in guacamole?",
    ["Mango", "Avocado", "Lime", "Banana"],
    "Avocado",
    "Guacamole is a dip made primarily from avocados.",
    "Green flesh, one large pit.",
    "https://www.britannica.com/plant/avocado",
  ],
  [
    "Space",
    "Which planet is closest to the Sun?",
    ["Venus", "Earth", "Mars", "Mercury"],
    "Mercury",
    "Mercury is the innermost planet in our solar system.",
    "It shares a name with a Roman messenger.",
    "https://science.nasa.gov/mercury/",
  ],
  [
    "Literature",
    "Who wrote Pride and Prejudice?",
    ["Jane Austen", "Charlotte Brontë", "Virginia Woolf", "George Eliot"],
    "Jane Austen",
    "Jane Austen published Pride and Prejudice in 1813.",
    "She also wrote Emma.",
    "https://www.britannica.com/topic/Pride-and-Prejudice",
  ],
  [
    "Science",
    "What force keeps planets in orbit around the Sun?",
    [],
    "Gravity",
    "Gravity is the attraction between masses that governs planetary orbits.",
    "Newton famously studied this force.",
    "https://science.nasa.gov/solar-system/",
  ],
  [
    "Geography",
    "What is the capital of France?",
    [],
    "Paris",
    "Paris is the capital of France.",
    "Its skyline includes the Eiffel Tower.",
    "https://www.britannica.com/place/Paris",
  ],
  [
    "Science",
    "What is the nearest star to Earth?",
    [],
    "Sun",
    "The Sun is the star at the center of our solar system.",
    "It supplies our daylight.",
    "https://science.nasa.gov/sun/",
  ],
].map(([category, prompt, choices, answer, explanation, hint, source], i) => ({
  category,
  prompt,
  choices,
  answer,
  explanation,
  hint,
  source,
  aliases: [],
  difficulty: i < 4 ? 1 : i < 8 ? 2 : 3,
  seconds: i < 8 ? 25 : 30,
  round: [
    "Warmup",
    "Culture",
    "Curveball",
    "The Wager",
    "Final Boss",
    "Global Final",
  ][Math.floor(i / 2)],
}));
